/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ahyaghifari.aplikasipenampilgambar;

import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Ahya Ghifari
 */
public class PilihGambarComboBox extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarComboBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        buttonPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbGambar = new javax.swing.JComboBox<>();
        imagePanel = new javax.swing.JPanel();
        lbSuperman = new javax.swing.JLabel();
        lbBatman = new javax.swing.JLabel();
        btnBlackAdam = new javax.swing.JLabel();
        lblAquaman = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pilih Gambar");
        buttonPanel.add(jLabel1);

        cbGambar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Superman", "Batman", "Black Adam", "Aquaman", "Keluar" }));
        cbGambar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbGambarItemStateChanged(evt);
            }
        });
        buttonPanel.add(cbGambar);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        imagePanel.setLayout(new java.awt.CardLayout());

        lbSuperman.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSuperman.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahyaghifari\\Documents\\NetBeansProjects\\AplikasiPenampilGambar\\superman.jpg")); // NOI18N
        imagePanel.add(lbSuperman, "0");

        lbBatman.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBatman.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahyaghifari\\Documents\\NetBeansProjects\\AplikasiPenampilGambar\\batman.jpg")); // NOI18N
        imagePanel.add(lbBatman, "1");

        btnBlackAdam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBlackAdam.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahyaghifari\\Documents\\NetBeansProjects\\AplikasiPenampilGambar\\blackadam.jpg")); // NOI18N
        imagePanel.add(btnBlackAdam, "2");

        lblAquaman.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAquaman.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahyaghifari\\Documents\\NetBeansProjects\\AplikasiPenampilGambar\\aquaman.jpg")); // NOI18N
        imagePanel.add(lblAquaman, "3");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbGambarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbGambarItemStateChanged
        String value = cbGambar.getSelectedItem().toString();
        if(!value.equals("Keluar")){
            CardLayout cl = (CardLayout)(imagePanel.getLayout());
            cl.show(imagePanel, String.valueOf(cbGambar.getSelectedIndex()));
        }else{
            int keluar = JOptionPane.showConfirmDialog(this, "Yakin ingin keluar", "Keluar", JOptionPane.YES_NO_OPTION);
            if(keluar == 0){
                System.exit(0);
            }
        }
    }//GEN-LAST:event_cbGambarItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihGambarComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBlackAdam;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JComboBox<String> cbGambar;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBatman;
    private javax.swing.JLabel lbSuperman;
    private javax.swing.JLabel lblAquaman;
    // End of variables declaration//GEN-END:variables
}
